//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagmentStudents.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class College
    {
        public int ID { get; set; }
        public int ID_STUDENTA { get; set; }
        public int ID_GROUP { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Students Students { get; set; }
    }
}
